
version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'
  server:
    build: ./server
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    ports:
      - '4000:4000'
    restart: unless-stopped
  ml:
    build: ./ml_model
    ports:
      - '8000:8000'
    restart: unless-stopped
volumes:
  mongo_data:
